params:
    num_classes: 10
    batch_size: 16
    optimizer: 'SGD'
    loss_function: 'sparse_categorical_crossentropy'
    epochs: 10
    metrics: 'accuracy'
    validation_data_size: 5000

artifacts:
    model_name: model.h5
    artifact_dir: artifact
    model_dir: model

    