params:
    num_classes: 10
    batch_size: 16
    optimizer: 'SGD'
    loss_function: 'sparse_categorical_crossentropy'
    epochs: 1
    metrics: 'accuracy'
    validation_data_size: 5000
    patience: 1
    restore_best_weights: True

artifacts:
    artifacts_dir:  artifacts
    model_name: model.h5
    ckpd_model_name: ckpd.h5
    artifact_dir: artifact
    model_dir: model
    ckpd_dir: ckeckpoint_model

logs:
    logs_dir: logs_dir
    TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs 
